
run:
    /opt/hadoop-3.1.3/bin/hadoop jar ./target/mapred-1.0-SNAPSHOT.jar \
    com.ecollado.samples.mapred.KmerCounterProcess \
    /user/poncos/kmers/input/ERR188245_1_piece.fastq \
    /home/ecollado/kmer/output/piece2  -N 10000 -M 4 -T 0,0,1,0